"""Bundle gpu_run.py and its five local modules into ONE Kaggle script kernel, by concatenation.

A Kaggle script kernel takes a single code file. gpu_run imports recall_tasks, bias_fair,
parity_block, shift_arms and cpu_precheck, so unlike kaggle/kernel (self-contained) or
kaggle/assert (one module) this needs a real bundler. Everything is CONCATENATED FROM SOURCE -
nothing is retyped, because a retyped copy is the blind spot that let the tied map ship silently
untied while every check passed.

THE TRAP THIS EXISTS TO AVOID. shift_arms and cpu_precheck BOTH define a class named `Net`:

    shift_arms.Net    the transformer / gdn reference   -> gpu_run imports it as RefNet
    cpu_precheck.Net  the ParityBlock network           -> gpu_run imports it as ParityNet

Concatenating them in either order makes the second silently shadow the first. The transformer
ceiling would quietly become a ParityBlock, every number would still look plausible, and the
ceiling gate - the thing that decides whether any arm is readable - would be comparing the
architecture against itself. So each Net is ALIASED immediately after its module is emitted,
before the next one can shadow it, and the bundle asserts at run time that the two are distinct.

WHAT IS STRIPPED, and each is recorded rather than silently dropped:
  local imports        `from <local module> import ...` - the names are already in scope once
                       concatenated. Indented function-local imports are stripped too (none remain
                       after sink_floor was replaced; the rule stays for any future one).
  __future__           hoisted once to the top; Python requires it first after the docstring.
  __main__ blocks      every module's except gpu_run's, which is the entry point.
  import aliases       re-established explicitly: np_grad, RefNet, ParityNet.

usage: python build.py     (then: kaggle kernels push -p .)
       python build.py --dir=../triage --name=saryu-ceiling-triage MODE=ceiling_triage STEPS=30000
         KEY=VALUE pairs are baked in AHEAD of the P1 defaults, so the same verified modules ship
         as a different job without a second, retyped prelude.
"""
from __future__ import annotations

import hashlib
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2]          # experimental/memory
OUT = pathlib.Path(__file__).resolve().parent / 'saryu-p1.py'
FUTURE = 'from __future__ import annotations'
LOCAL = ('recall_tasks', 'bias_fair', 'parity_block', 'shift_arms', 'cpu_precheck', 'gpu_run')

#   dependency order, with the alias fixups each module owes its consumers
MODULES = [
    ('recall_tasks.py', []),
    ('bias_fair.py', ['np_grad = grad']),
    ('parity_block.py', []),
    ('shift_arms.py', ['RefNet = Net']),
    ('cpu_precheck.py', ['ParityNet = Net']),
    ('gpu_run.py', []),
]

PRELUDE = '''"""P1: do extra reads substitute for layers? Generated by build.py - do not edit.

THE CLAIM UNDER TEST. Hop budget multiplies across layers: ours is n_layers x n_read, theirs is
n_layers x 1. The controlled comparison is NL2 r4 against NL2 r1 - identical parameters and
layers, differing only in n_read - across chain depth, against depth-matched (NL2) and deep (NL8)
transformer baselines.

Read accuracy against FLOOR, the better of two query-free heuristics printed per depth: guessing
among sinks, and the dmode=edge shortcut (the sink whose source is also a target), which scores
1.000 at every depth on the v1-v4 task. Per-seed accuracies are printed; read gaps against them.

Sources concatenated verbatim from experiments/ by build.py. Nothing is retyped.
"""
from __future__ import annotations

import os
import subprocess
import sys

#   THE CHEAP PROBE SETTINGS, BAKED IN. Kaggle metadata cannot pass environment variables, so a
#   bundle without this would run gpu_run's DEFAULTS - STEPS=6000, D=256, DEPTHS=2,3,4,6, every
#   arm - which is the 5.5-hour full sweep, not the ~15-minute probe. Exactly the expensive run
#   we are trying to avoid committing to before P1 is answered.
#   setdefault, not assignment, so anything set outside still wins.
#   THE 30-MINUTE DESIGN, chosen after the eps ablation showed chain accuracy swinging 0.074 to
#   0.496 across seeds at IDENTICAL settings. A single-seed ordering between three arms would be
#   a coin flip, and P1 is an ordering claim - so the budget goes on SEEDS, not on breadth.
#
#   DEPTHS 2 AND 3, after v2 at depth 6 returned a pure null - every arm BELOW the sink floor,
#   transformer ceiling included at 0.049 against a floor of 0.143. Depth 6 is the most
#   DISCRIMINATIVE cell (NL2 r1 has budget 2 and provably cannot reach) but it is not LEARNABLE
#   at this scale, and ceiling_sweep had already said so: at 6000 steps even mqar-3 - one hop,
#   three pairs - reached only 0.292.
#
#   Depth 3 keeps the discrimination and drops most of the difficulty: with NL=2 it still exceeds
#   the layer count, so NL2 r1 remains budget-limited while NL2 r4 does not. Depth 2 rides along
#   as the control every arm should manage, and the ceiling then REPORTS which cells are readable
#   instead of my guessing a second time.
#
#   v4 DROPS NL8 r1 AND ADDS DEPTH 4. v3 showed NL8 r1 at 0.374 on depth 3 - WORSE than NL2 r1's
#   0.586 despite hop budget 8 against 2 - which the budget model cannot produce. An 8-layer model
#   simply does not train in 3000 steps, so that arm measured trainability, not capacity, and any
#   parameter-efficiency claim resting on it would be a win over a baseline weak for the wrong
#   reason. Buying it a fair fight needs 8000+ steps; that is a later run, not this one.
#
#   What v3 DID establish is clean, because NL2 r1 and NL2 r4 have IDENTICAL parameters (341,947)
#   and identical layers, differing only in n_read: 0.997 -> 1.000 at depth 2 (reads unnecessary)
#   and 0.586 -> 0.879 at depth 3 (reads necessary). Depth 4 asks whether that gap WIDENS, which a
#   single point cannot show and a trend across three depths can. Sink floor there is 0.200, and
#   depth 4 at ratio 1.0 needs 5 + 8 = 13 entities against NENT=32, so batch() cannot hang.
#
#   NENT=32 is not arbitrary. depth=6 at ratio=1.0 needs (depth+1) + 2*round(depth*ratio) = 19
#   distinct entities; at NENT=16 make_chain returns None every time and batch() loops forever
#   waiting for a sequence that cannot be built.
#
#   v5 (audit 2026-09-15). ARMS was still 'ceiling_NL8,...' after 08fe8b3 added the depth-matched
#   NL2 ceiling, so a plain rebuild would have picked up CEIL_MULT and silently never run the new
#   arm. 'ceiling' now selects BOTH. The task default is dmode=chain (gpu_run), because the v1-v4
#   task has a query-free shortcut scoring 1.000 at every depth; set DMODE=edge to reproduce them.
#@OVERRIDES@
for _k, _v in (('STEPS', '3000'), ('SEEDS', '0,1,2'), ('D', '128'), ('HEAD_DIM', '64'),
               ('NENT', '32'), ('DEPTHS', '2,3,4'), ('DMODE', 'chain'), ('RATIO', '1.0'),
               ('ARMS', 'ceiling,tied_NL2_r4,tied_NL2_r1')):
    os.environ.setdefault(_k, _v)
print('BUNDLE ENV  ' + '  '.join('%s=%s' % (k, os.environ.get(k, '-')) for k in (
    'MODE', 'STEPS', 'SEEDS', 'D', 'HEAD_DIM', 'NENT', 'DEPTHS', 'DMODE', 'RATIO', 'ARMS')), flush=True)

#   PINNED. 0.5.2 is the newest release before v4 ran (2026-09-14) and so the one whose kernel
#   matched our loop; an unpinned install could pick up a layout or signature change mid-series.
print('installing flash-linear-attention==0.5.2 ...', flush=True)
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'flash-linear-attention==0.5.2'],
               check=False)

'''

GUARD = '''

# ---------------------------------------------------------------- bundle integrity
#   shift_arms.Net and cpu_precheck.Net share a name; if concatenation shadowed one, the
#   transformer ceiling would silently be a ParityBlock and the gate would compare the
#   architecture against itself while every number still looked plausible.
assert RefNet is not ParityNet, 'BUNDLE BROKEN: the two Net classes were collapsed into one'
#   identity is necessary but not sufficient - check each actually builds the mixer it should.
#   (the first version of this line read `assert 'Attn' in ... or True`, a tautology that could
#   never fail. A vacuous assert is worse than none: it reads as coverage and provides none.)
_a = type(RefNet('transformer', 16, 64, 1).mix[0]).__name__
_b = type(ParityNet(16, 64, 1, head_dim=32, channel_gates=False, tied=True, n_read=2).mix[0]).__name__
assert _a == 'Attn', 'RefNet builds %s, not attention - the ceiling would be a ParityBlock' % _a
assert _b == 'ParityBlock', 'ParityNet builds %s, not ParityBlock' % _b
print('bundle integrity: RefNet mixer=%s  ParityNet mixer=%s  distinct=%s'
      % (_a, _b, RefNet is not ParityNet), flush=True)
del _a, _b

'''


def strip(text: str, drop_main: bool) -> str:
    if drop_main:
        text = re.split(r'^if __name__ ==', text, maxsplit=1, flags=re.M)[0]
    out = []
    for line in text.splitlines(keepends=True):
        s = line.strip()
        if s == FUTURE:
            continue
        if re.match(r'^\s*from\s+(%s)\s+import\s' % '|'.join(LOCAL), line):
            continue
        if re.match(r'^\s*import\s+(%s)\s*$' % '|'.join(LOCAL), line):
            continue
        out.append(line)
    return ''.join(out)


if __name__ == '__main__':
    import sys
    out, sets = OUT, []
    for a in sys.argv[1:]:
        if a.startswith('--dir='):
            out = pathlib.Path(a[len('--dir='):]).resolve() / out.name
        elif a.startswith('--name='):
            out = out.parent / (a[len('--name='):] + '.py')
        elif '=' in a:
            sets.append(tuple(a.split('=', 1)))
        else:
            raise SystemExit('unrecognised argument: %s' % a)
    assert PRELUDE.count('#@OVERRIDES@\n') == 1, 'override marker missing from PRELUDE'
    over = ''.join('os.environ.setdefault(%r, %r)\n' % kv for kv in sets)
    chunks, digests = [PRELUDE.replace('#@OVERRIDES@\n', over)], []
    for i, (name, aliases) in enumerate(MODULES):
        p = ROOT / name
        raw = p.read_bytes()
        digests.append((name, hashlib.sha256(raw).hexdigest()[:12]))
        body = strip(raw.decode('utf-8'), drop_main=(name != 'gpu_run.py'))
        chunks.append('\n# %s\n# --- from experiments/%s ---\n' % ('=' * 76, name))
        chunks.append(body)
        for a in aliases:
            chunks.append('\n%s\n' % a)
        if name == 'cpu_precheck.py':
            chunks.append(GUARD)
    out.write_text(''.join(chunks), encoding='utf-8')
    print('generated %s  (%d bytes)%s' % (out, out.stat().st_size,
                                          ''.join('  %s=%s' % kv for kv in sets)))
    for n, h in digests:
        print('  %-20s sha256 %s' % (n, h))
