"""Does the model UNTANGLE its manifolds before it needs them? A position profile.

THE RESULT BEING TESTED. "Emergent Manifold Separability during Reasoning in Large Language Models"
(arXiv 2602.20338, 2026) applies manifold capacity along the TEMPORAL axis and reports a transient
geometric pulse: concept manifolds are untangled into linearly separable subspaces immediately
before the computation that needs them, then rapidly recompressed. They call it Dynamic Manifold
Management -- the model modulating its own representational bandwidth across the sequence.

Every application of manifold capacity so far (Gardner -> Chung/Lee/Sompolinsky -> Mamou 2020 ->
2602.20338) is to a FEEDFORWARD residual stream. Nobody has run it on a recurrent state, where the
manifold is generated by the TRANSPORT rather than by input variation.

WHAT IS MEASURED. Pick one stored pair. Across many sequences, vary its value over C classes and
randomise everything else. At every position t, take the residual stream and ask three things:

    sep    linear separability of that value's class -- can a probe read it here at all
    R_M    manifold radius: spread within a class about its centre
    D_M    manifold dimension: participation ratio of the within-class covariance
    corr   mean |cosine| between class CENTRES -- the third variable in the capacity formula,
           which orbit_manifold.py omits. Capacity falls as centres become correlated even when
           radius is small.

Manifold capacity alpha_M = P/N is predicted by exactly (R_M, D_M, centre correlation), with small
values of each giving larger capacity. So this profile says both WHERE the information is legible
and WHAT geometry makes it legible or not.

REGISTERED PREDICTIONS, before running:
  P1  at 2 pairs, which this model solves, separability is high near the query position -- either
      sustained or pulsing, per 2602.20338.
  P2  at 4 pairs, which it never solves, separability decays with distance from the write and is at
      chance by the query. This is already known from the probes; the new content is the SHAPE.
  P3  the difference between the regimes shows up in R_M or centre correlation, not only in sep --
      i.e. there is a geometric cause visible before separability collapses.

FALSIFIER for the pulse account: the n=2 profile is flat, with no rise approaching the query. Then
this model does not do dynamic manifold management at all, and its success at 2 pairs has nothing
to do with untangling -- so the mechanism is not what separates the two regimes.

    python evidence/manifold_pulse.py
Environment: NPAIRS, CLASSES, GAP, STEPS, D, H, NL, NH, N_SEQ, SEED, THREADS.
"""
from __future__ import annotations

import os
import sys

import numpy as np
import torch
import torch.nn.functional as F

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from saryu.model import SaryuV3LM                                     # noqa: E402
from binding_long import Muon                                        # noqa: E402

PAIRS = [int(x) for x in os.environ.get('NPAIRS', '2,4').split(',')]
CLASSES = int(os.environ.get('CLASSES', 8))
GAP = int(os.environ.get('GAP', 4))
STEPS = int(os.environ.get('STEPS', 3000))
D = int(os.environ.get('D', 128))
H = int(os.environ.get('H', 8))
NL = int(os.environ.get('NL', 2))
NH = int(os.environ.get('NH', 2))
N_SEQ = int(os.environ.get('N_SEQ', 1600))
SEED = int(os.environ.get('SEED', 0))
NENT = 64
SEP = NENT
torch.set_num_threads(int(os.environ.get('THREADS', 2)))
VCLS = list(range(CLASSES))                      # the C candidate values for the tracked pair


def seq_with(rng, n, vclass):
    """Sequence whose FIRST pair carries value `vclass`; everything else resampled."""
    pool = np.setdiff1d(np.arange(NENT), np.array(VCLS))
    ent = rng.choice(pool, size=2 * n - 1, replace=False)
    ks = [int(ent[0])] + [int(x) for x in ent[1:n]]
    vs = [int(vclass)] + [int(x) for x in ent[n:2 * n - 1]]
    rest = np.setdiff1d(pool, ent)
    s = []
    for k, v in zip(ks, vs):
        s += [k, v]
    s += [int(x) for x in rng.choice(rest, size=GAP, replace=True)]
    i = int(rng.integers(0, n))
    s += [SEP, ks[i]]
    return s


def train(n, seed):
    torch.manual_seed(seed)
    m = SaryuV3LM(NENT + 2, D, NL, nh=NH, H=H)
    p = list(m.parameters())
    opt = Muon(p, lr=3e-4)
    rng = np.random.default_rng(1000 + seed)
    for _ in range(STEPS):
        xs, ys = [], []
        for _ in range(32):
            ent = rng.choice(NENT, size=2 * n, replace=False)
            ks, vs = ent[:n], ent[n:]
            s = []
            for k, v in zip(ks, vs):
                s += [int(k), int(v)]
            rest = np.setdiff1d(np.arange(NENT), ent)
            s += [int(z) for z in rng.choice(rest, size=GAP, replace=True)]
            i = int(rng.integers(0, n))
            s += [SEP, int(ks[i])]
            xs.append(s); ys.append(int(vs[i]))
        x, y = torch.tensor(xs), torch.tensor(ys)
        ce = F.cross_entropy(m(x)[:, -1], y)
        opt.zero_grad(); ce.backward()
        torch.nn.utils.clip_grad_norm_(p, 1.0); opt.step()
    m.eval()
    return m


@torch.no_grad()
def stream(m, x):
    """Residual stream at every position, after the final norm."""
    h = m.emb(x)
    ve = m.vemb(x) if m.vemb is not None else None
    for mix, ffn in zip(m.mix, m.ffn):
        h = h + mix(h, ve)
        h = h + ffn(h)
    return m.lnf(h)


def geometry(Z, y, C):
    """R_M, D_M and mean |cos| between class centres -- the three capacity variables."""
    cents, rads, dims = [], [], []
    for c in range(C):
        A = Z[y == c]
        if len(A) < 8:
            continue
        mu = A.mean(0); cents.append(mu)
        Ac = A - mu
        rads.append(float(Ac.norm(dim=-1).mean() / (mu.norm() + 1e-9)))
        lam = torch.linalg.eigvalsh(Ac.T @ Ac / len(Ac)).clamp_min(0)
        dims.append(float(lam.sum() ** 2 / (lam ** 2).sum()))
    Cn = F.normalize(torch.stack(cents), dim=-1)
    G = (Cn @ Cn.T).abs()
    off = G[~torch.eye(len(Cn), dtype=torch.bool)]
    return float(np.mean(rads)), float(np.mean(dims)), float(off.mean())


def probe(Z, y, C, ep=200, lr=0.08):
    k = int(len(y) * 0.8)
    a, b = Z[:k], Z[k:]
    ya, yb = y[:k], y[k:]
    mu, sd = a.mean(0, keepdim=True), a.std(0, keepdim=True) + 1e-6
    a, b = (a - mu) / sd, (b - mu) / sd
    W = torch.zeros(Z.shape[1], C, requires_grad=True)
    B = torch.zeros(C, requires_grad=True)
    o = torch.optim.Adam([W, B], lr=lr)
    for _ in range(ep):
        loss = F.cross_entropy(a @ W + B, ya)
        o.zero_grad(); loss.backward(); o.step()
    with torch.no_grad():
        return float(((b @ W + B).argmax(-1) == yb).float().mean())


def main():
    print(f'MANIFOLD PULSE  tracking one stored value over {CLASSES} classes, {N_SEQ} sequences')
    print('does separability RISE approaching the query position (untangling) or decay?\n')
    for n in PAIRS:
        m = train(n, SEED)
        rng = np.random.default_rng(31337)
        xs, ys = [], []
        for _ in range(N_SEQ):
            c = int(rng.integers(0, CLASSES))
            xs.append(seq_with(rng, n, VCLS[c])); ys.append(c)
        x, y = torch.tensor(xs), torch.tensor(ys)
        Zs = stream(m, x)
        L = x.shape[1]
        qpos = L - 1
        print(f'--- {n} pairs   (value written at position 1, query key at position {qpos}) ---')
        print(f'{"pos":>4} {"token":>7} {"sep":>7} {"R_M":>7} {"D_M":>7} {"corr":>7}')
        for t in range(L):
            Z = Zs[:, t]
            sep = probe(Z, y, CLASSES)
            R, DM, cr = geometry(Z, y, CLASSES)
            tag = ('val*' if t == 1 else 'key' if t % 2 == 0 and t < 2 * n else
                   'val' if t < 2 * n else 'fill' if t < 2 * n + GAP else
                   'SEP' if t == L - 2 else 'query')
            print(f'{t:>4} {tag:>7} {sep:>7.3f} {R:>7.3f} {DM:>7.1f} {cr:>7.3f}', flush=True)
        print()
    print('READ')
    print('  sep rises toward the query at n=2 -> dynamic manifold management is present and its')
    print('                                       absence at n=4 is the mechanism')
    print('  sep flat or decaying at both      -> no pulse here; the 2026 result does not describe')
    print('                                       this architecture')


if __name__ == '__main__':
    main()
