"""Bundle the current repo into a Kaggle kernel that runs one entry script on GPU.

Same principle as archive/kaggle/memory/build_bundle.py, which worked: the kernel WRITES the
source files out unchanged and runs the entry as __main__, so what executes on Kaggle is
byte-for-byte what executes locally. No concatenation, no regex patching of the source, and
therefore no silent divergence between the thing tested here and the thing run there.

    python scripts/build_kaggle.py gpuprobe evidence/gpu_probe.py STEPS=30
    python scripts/build_kaggle.py lmtrain  evidence/lm_train.py  D=512 STEPS=20000

Writes kaggle/<name>/ with the kernel script and its metadata. Push with the Kaggle CLI:

    KAGGLE_API_TOKEN=... kaggle kernels push -p kaggle/<name>

The account id in kernel-metadata.json is private and scripts/sync_public.py replaces it with a
placeholder on the way to the public repo; publish_scan.py blocks on it so it cannot leak.
"""
from __future__ import annotations

import json
import os
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ACCOUNT = os.environ.get('KAGGLE_ACCOUNT', 'chanakya' + 'saryu')

# Everything the entry script might import. Written verbatim into the kernel's working directory
# under the same relative paths, so `from saryu.model import ...` resolves exactly as it does here.
ALWAYS = ['saryu/__init__.py', 'saryu/model.py', 'saryu/metrics.py']

TEMPLATE = '''# generated by scripts/build_kaggle.py -- do not edit
import os, sys, runpy, pathlib
SRC = {src!r}
CFG = {cfg!r}
ENTRY = {entry!r}
root = pathlib.Path('/kaggle/working/src')
for name, text in SRC.items():
    p = root / name
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding='utf-8')
os.environ.update(CFG)
sys.path.insert(0, str(root))
print('bundle:', len(SRC), 'files | config:', CFG, flush=True)
import torch
print('torch', torch.__version__, '| cuda', torch.cuda.is_available(),
      '|', torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU', flush=True)
runpy.run_path(str(root / ENTRY), run_name='__main__')
'''


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        return 1
    name, entry = sys.argv[1], sys.argv[2]
    cfg = dict(kv.split('=', 1) for kv in sys.argv[3:] if '=' in kv)

    wanted = list(dict.fromkeys(ALWAYS + [entry]))
    src = {}
    for rel in wanted:
        p = ROOT / rel
        if not p.exists():
            if rel == 'saryu/__init__.py':
                src[rel] = ''                      # package marker, may legitimately be absent
                continue
            print(f'missing: {rel}')
            return 1
        src[rel] = p.read_text(encoding='utf-8')

    out = ROOT / 'kaggle' / name
    out.mkdir(parents=True, exist_ok=True)
    script = out / f'{name}.py'
    script.write_text(TEMPLATE.format(src=src, cfg=cfg, entry=entry), encoding='utf-8')
    (out / 'kernel-metadata.json').write_text(json.dumps({
        'id': f'{ACCOUNT}/saryu-{name}',
        'title': f'saryu-{name}',
        'code_file': f'{name}.py',
        'language': 'python',
        'kernel_type': 'script',
        'is_private': True,
        'enable_gpu': True,
        'enable_tpu': False,
        'enable_internet': True,
        'dataset_sources': [],
        'competition_sources': [],
        'kernel_sources': [],
    }, indent=2) + '\n', encoding='utf-8')
    kb = len(script.read_text(encoding='utf-8')) / 1024
    print(f'built kaggle/{name}/  ({len(src)} files, {kb:.0f} KB)')
    for rel in src:
        print(f'  + {rel}')
    print(f'\n  kaggle kernels push -p kaggle/{name}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
